Stringify event.data in handlers
alexandrebodin/hapi-good-winston pull request #3
Opened 2016-12-26 22:05 UTC by gamtiq

I have added stringifying of event.data objects (like in [good-console](https://github.com/hapijs/good-console/blob/master/lib/index.js) and [SafeJson from good-squeeze](https://github.com/hapijs/good-squeeze/blob/master/lib/safe-json.js)). Now data objects are written into a log more appropriate (instead of `[object Object]`).

2017-01-03 16:07 UTC, alexandrebodin commented
Sorry for the delay I'll take a look at it in the coming days

2017-01-05 17:38 UTC, alexandrebodin commented on lib/handlers.js
> +    return data && typeof data === 'object'
Can you please return an empty string if data is undefined (much cleaner that printing undefined)

2017-01-05 17:38 UTC, alexandrebodin requested changes
Just a minor change

2017-01-05 21:17 UTC, gamtiq commented
I have made the change.

2017-01-05 21:31 UTC, merged